version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend  
    networks:
      - mern-network

  backend:
    build: ./backend
    ports:
      - "3002:3002"
    depends_on:
      - database  
    networks:
      - mern-network

  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - "G:/wed_project/mongo-backup:/data/db"  
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
